### PR TITLE
Logs to std out and fixed #124

### LINKED ISSUE #124: [BUG] kimai/kimai2:apache-debian-master-dev runs in prod env
**Describe the bug**
The dev image runs as prod

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container 'docker run -p 8001:8001 --name kimaitmp --rm -v $(pwd)/logs:/opt/kimai/var/log kimai/kimai2:apache-debian-master-dev'
2. Hit the index page, no dev toolbar
3. Shell onto box and check logs folder, onlt the prod log

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker version: 19.03.8
 - Docker compose version: 1.25.0

**Command used to run the container**
 - docker run -p 8001:8001 --name kimaitmp --rm -v $(pwd)/logs:/opt/kimai/var/log kimai/kimai2:apache-debian-master-dev

**Docker compose file (with passwords redacted)**

### PR DESCRIPTION
**Pull request by tobybatch**
This sends the logs to the console.

### CODE REVIEW

File: startup.sh [hunk 1]
```diff
@@ -32,12 +32,31 @@ function handleStartup() {
     if [ ! -z "$ADMINPASS" ] && [ ! -a "$ADMINMAIL" ]; then
       /opt/kimai/bin/console kimai:create-user superadmin $ADMINMAIL ROLE_SUPER_ADMIN $ADMINPASS
     fi
+    # I think kimai:install overwrites the monolog config
```
Comment (kevinpapst) [inline startup.sh]: no, it doesn't 😁

File: startup.sh [hunk 2]
```diff
@@ -32,12 +32,31 @@ function handleStartup() {
...
+      level: error
+EOF
+    fi
     echo $KIMAI > /opt/kimai/installed
   fi
   echo "Kimai2 ready"
 }
 
 function runServer() {
+  /opt/kimai/bin/console cache:clear --env=$APP_ENV
```
Comment (kevinpapst) [inline startup.sh]: either add a `/opt/kimai/bin/console cache:warmup --env=$APP_ENV` or use the reload command `/opt/kimai/bin/console kimai:reload --env=$APP_ENV`

File: startup.sh [hunk 3]
```diff
@@ -32,12 +32,31 @@ function handleStartup() {
...
+      cat <<EOF > /opt/kimai/config/packages/dev/monolog.yaml
+monolog:
+  handlers:
+    main:
+      type: error_log
+      level: debug
+EOF
+    else 
+      cat <<EOF > /opt/kimai/config/packages/prod/monolog.yaml
+monolog:
```
Comment (kevinpapst) [inline startup.sh]: this config looks different than the [default kimai monolog config](https://github.com/kevinpapst/kimai2/blob/master/config/packages/prod/monolog.yaml) - on purpose?

Comment (tobybatch) [reply startup.sh]: Yes, that's the fix. It redirects the output the server log so that it runs in the foreground and dumps to stdout.  That way the logs are visible when running the docker.

File: startup.sh (hunk 1 above)
Comment (tobybatch) [reply startup.sh]: Hmm.  I'll investigate.

File: startup.sh (hunk 2 above)
Comment (tobybatch) [reply startup.sh]: Done

**Comment by tobybatch** [comment]
@kevinpapst Switched to adding config files during build

**Review by kevinpapst — APPROVED** [review]
Using files instead of `cat` is much better to understand and could help other users in improving stuff for their own situation. As always: I haven't tested it. But it looks good to me 👍
